### PR TITLE
Added class to handle choosing who goes first between user and their opp...

### PR DESCRIPTION
**Pull request by pumpkincouture**
Added feature to game to choose who goes first in the game.

### CODE REVIEW

**Comment by tarynsauer** [comment]
In the Game class, there seems to be a lot of redundancy between the getFirstMove(playerOne) and getSecondMove(playerTwo) functions. Try to refactor this to a single getPlayerMove(player) function.

**Comment by tarynsauer** [comment]
You chain player.getClass().getSimpleName() several times. You could probably make a public getName() function in the Player class that encapsulates this. It would look cleaner too.

**Comment by tarynsauer** [comment]
It seems like the new PlayerOrder class's responsibility is pretty similar to that of the GameConfiguration class.It gets configuration info from the user and then sets up the data for Game accordingly. What do you think about putting PlayerOrder in GameConfiguration?

**Comment by pumpkincouture** [comment]
Hi both -

I incorporated changes, let me know if it looks good to merge!

**Pull request merged**
